// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACV_Ju0axcdkftSSQk26AYObcBgqVYz50',
    appId: '1:572673771369:android:8e6eed34502dd6b7685ff8',
    messagingSenderId: '572673771369',
    projectId: 'doingbusinessbygrantthorntondz',
    storageBucket: 'doingbusinessbygrantthorntondz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPUAps81yN-N0jJYLxYDMc0p9Uupcfu-8',
    appId: '1:572673771369:ios:6f7bbac9e7ec542b685ff8',
    messagingSenderId: '572673771369',
    projectId: 'doingbusinessbygrantthorntondz',
    storageBucket: 'doingbusinessbygrantthorntondz.firebasestorage.app',
    iosBundleId: 'com.grantthorntondz.doingbusiness',
  );
}
